#!/usr/bin/env bash

# build a known user of this lib
GO111MODULE=off go get github.com/insomniacslk/dhcp/examples/client6/...
cd "${GOPATH}/src/github.com/insomniacslk/dhcp"
GO111MODULE=off go build github.com/insomniacslk/dhcp/examples/client6/...
